name: Publish Release

on:
  release:
    types: [published]
jobs:
  List-languages:
    runs-on: ubuntu-latest
    outputs:
      matrix-langs: ${{ steps.langs.outputs.matrix-langs }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Get the list of languages for the matrix
        id: langs
        run: |
          output="::set-output name=matrix-langs::["
          cd se.data/langs
          for entry in `ls`; do 
              if [ "$entry" != "en_us.json" ]; then
                  output+="\"$entry\", "
              fi
          done
          output=${output:0:-2}
          output+="]"
          echo $output
  Publish-App:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Upload ScarpetEdit app
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: se.sc
          asset_name: se.sc
          asset_content_type: text/plain
  Publish-Language:
    runs-on: ubuntu-latest
    needs: [List-languages]
    strategy:
      matrix:
        lang: ${{ fromJson(needs.List-languages.outputs.matrix-langs) }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Upload ${{ matrix.lang }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: se.data/langs/${{ matrix.lang }}
          asset_name: ${{ matrix.lang }}
          asset_content_type: application/json
